spring:
  datasource:
    username: postgres
    password: Morsko11
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    show-sql: true



server:
  port: 8081
